#!/bin/bash
# Build skill index from generated skills for fast lookup

SKILLS_DIR="${1:-.claude/skills}"
OUTPUT_FILE="${2:-.claude/hooks/lib/skill-index.json}"

# Create output directory if it doesn't exist
OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
mkdir -p "$OUTPUT_DIR"

# Check if skills directory exists
if [ ! -d "$SKILLS_DIR" ]; then
  echo "{}" > "$OUTPUT_FILE"
  exit 0
fi

# Start JSON array
echo "[" > "$OUTPUT_FILE"

first=true

# Scan all .md files in skills directory
for skill_file in "$SKILLS_DIR"/*.md; do
  [ -f "$skill_file" ] || continue

  # Check if generated by discover-project-skills
  if ! grep -q "<!-- Generated by discover-project-skills" "$skill_file"; then
    continue
  fi

  # Extract skill name from filename
  skill_name=$(basename "$skill_file" .md)

  # Extract invocation metadata
  # Look for: <!-- Invocation metadata:
  #   paths: src/api/, src/routes/
  #   keywords: REST, endpoint, HTTP
  #   tech: ktor, kotlin
  # -->

  # Extract paths line
  paths_line=$(grep -A 10 "Invocation metadata:" "$skill_file" | grep "paths:" | head -1)
  paths=$(echo "$paths_line" | sed 's/.*paths: //' | sed 's/-->.*//')

  # Extract keywords line
  keywords_line=$(grep -A 10 "Invocation metadata:" "$skill_file" | grep "keywords:" | head -1)
  keywords=$(echo "$keywords_line" | sed 's/.*keywords: //' | sed 's/-->.*//')

  # Extract tech line
  tech_line=$(grep -A 10 "Invocation metadata:" "$skill_file" | grep "tech:" | head -1)
  tech=$(echo "$tech_line" | sed 's/.*tech: //' | sed 's/-->.*//')

  # Build JSON entry
  if [ "$first" = true ]; then
    first=false
  else
    echo "," >> "$OUTPUT_FILE"
  fi

  cat >> "$OUTPUT_FILE" <<EOF
  {
    "name": "$skill_name",
    "file": "$skill_file",
    "paths": ["$(echo $paths | sed 's/, /", "/g')"],
    "keywords": ["$(echo $keywords | sed 's/, /", "/g')"],
    "tech": ["$(echo $tech | sed 's/, /", "/g')"]
  }
EOF

done

# Close JSON array
echo "]" >> "$OUTPUT_FILE"

# Print summary
skill_count=$(jq length "$OUTPUT_FILE" 2>/dev/null || echo "0")
echo "Built skill index: $skill_count skills" >&2
